config/routes.rb
Rails.application.routes.draw do

  resources :brokentoolreportsheets
 
  resources :users
  
  resources :factories
  
  resources :vendingmachines
  
  resources :stockchecksheets
  
  resources :faultsheets
  
  resources :vendingmachines do
    resources :stockchecksheets
  end
  
  get 'vendingmachines/:id/stockchecksheets', to: 'stockchecksheets#checkstock'
  
  root 'welcome#index'
  

end

app/models/brokentoolreportsheet.rb
class Brokentoolreportsheet < ActiveRecord:: Base
  validates :toolname,  length: {minimum: 5}
  validates :toolfault,  length: {minimum: 20}
  validates :toollocation,  length: {minimum: 3}
end

app/models/factory.rb
class Factory < ActiveRecord::Base
  has_many :vendingmachines
  has_many :stockchecksheets, through: :vendingmachines
end

app/models/faultsheet.rb
class Faultsheet < ActiveRecord::Base
  
  belongs_to :vendingmachine
  
end

app/models/stockchecksheet.rb
class Stockchecksheet < ActiveRecord::Base
  
   belongs_to :vendingmachine

end

app/models/user.rb
class User < ActiveRecord::Base

end

app/models/vendingmachine.rb
class Vendingmachine < ActiveRecord::Base
  
  belongs_to :factory
  has_many :stockchecksheets
  has_many :faultsheets
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
  end
end

app/controllers/brokentoolreportsheets_controller.rb
class BrokentoolreportsheetsController < ActionController::Base
  
  # new action creates a new ActiveRecord
  def new
    # @brokentoolreportsheet is a local variable
    @brokentoolreportsheet = Brokentoolreportsheet.new()
  end
  
  # create action saves the ActiveRecord data to DB
  def create
    @brokentoolreportsheet = Brokentoolreportsheet.new(tool_params)
    @brokentoolreportsheet.save
    
    #redirects to last recorded report for SFR7 for UC01
    redirect_to @brokentoolreportsheet
  end
  
  # show action finds and stores the record corresponding to the id
  def show
    @brokentoolreportsheet = Brokentoolreportsheet.find(params[:id])
  end
  
  # stores all the record in @brokentoolreportsheets variable
  def index
    @brokentoolreportsheets = Brokentoolreportsheet.all
  end
  
  # private method called in the create function 
  # defines the tool parameters
  private 
    def tool_params
      params.require(:brokentoolreportsheet).permit(:toolname, :toolfault, :toollocation)
    end
end

app/controllers/factories_controller.rb
class FactoriesController < ActionController::Base

  def new
    @factory = Factory.new()
  end
  
  def create
    @factory = Factory.new(factory_params)
    @factory.save
    redirect_to @factory
    
  end

  def index
    @factories = Factory.all
  end
  
  def show
    @factory = Factory.find(params[:id])
  end

  
  
  private 
    def factory_params
      params.require(:factory).permit(:name, :address)
    end

end

app/controllers/faultsheets_controller.rb
class FaultsheetsController < ActionController::Base
  
  def new
    @faultsheet = Faultsheet.new()
  end
  
  def create
    @faultsheet = Faultsheet.new(faultsheet_params)
    @faultsheet.save
    redirect_to @faultsheet
    
  end
  
  def show
    @faultsheet = Faultsheet.find(params[:id])
  end
  
  private 
    def faultsheet_params
      params.require(:faultsheet).permit(:fault, :vendingmachine_id)
    end

end

app/controllers/stockchecksheets_controller.rb
class StockchecksheetsController < ActionController::Base

  def index
    @sheet = Stockchecksheet.all
  end
  
  def create
    @sheet = Stockchecksheet.new(stockchecksheet_params)
    @sheet.save
    redirect_to @sheet
  end
  
  def show
    @sheet = Stockchecksheet.find(params[:id])
  end
  
  def new
    @sheet = Stockchecksheet.new()
    @vendingmachine = @sheet.vendingmachine_id
  end
  
  def update
    @sheet = Stockchecksheet.find(params[:id])
    if @sheet.update(stockchecksheet_params)
      redirect_to @sheet
    else
      render 'show'
    end
  end
  
  private 
    def stockchecksheet_params
      params.require(:stockchecksheet).permit(:item1, :item2, :item3, :item4, :item5, 
                                              :item11, :item12, 
                                              :item21, :item22,
                                              :item31, :item32,
                                              :item41, :item42,
                                              :item51, :item52,
                                              :vendingmachine_id)
    end
    
    
    
end

app/controllers/vendingmachines_controller.rb
class VendingmachinesController < ActionController::Base
  
  def index
    @vendingmachines = Vendingmachine.all
  end
  
  def new
    @vendingmachine = Vendingmachine.new()
  end
  
  def create
    @vendingmachine = Vendingmachine.new(vendingmachine_params)
    #@vendingmachine.factory = Factory.first
    @vendingmachine.save
    redirect_to @vendingmachine
  end
  
  def show
    @vendingmachine = Vendingmachine.find(params[:id])
    @stockchecksheets = @vendingmachine.stockchecksheets
  end
  
  private 
    def vendingmachine_params
      params.require(:vendingmachine).permit(:title, :configuration, :factory_id)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base

 def index
  
 end
 
 def home
   
 end
 
 def show
 
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brokentoolreportsheets/index.html.erb
<h1>Broken tool collection records</h1>
<%= link_to "Record new broken tool for collection", new_brokentoolreportsheet_path %>
<p><%= link_to "Home", root_path %></p>
<% @brokentoolreportsheets.each do |f| %>
<h2><%= f.toolname %></h2>
<p><%= f.toolfault %></p>
<p><%= f.toollocation %></p>
<% end %>
<p><%= link_to "Record new broken tool for collection", new_brokentoolreportsheet_path %><p>
<p><%= link_to "Home", root_path %></p>

app/views/brokentoolreportsheets/new.html.1.erb
<h1>Report new broken tool for collection</h1>

<%= form_for @brokentoolreportsheet do |f| %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@brokentoolreportsheet, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :toolname %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :toolname, class: "form-control", placeholder: "Name of tool", autofocus: true %>
        </div>
      </div>
      
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :toolfault %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :toolfault, rows:10, class: "form-control", placeholder: "Description of fault" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :toollocation %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :toollocation, class: "form-control", placeholder: "Factory name" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit :onclick =>"return confirm('Sure')", class: "btn btn-primary btn-lg" %>
        </div>
      </div>
      
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
       [ <%= link_to "Cancel request and return to all tool faulty tool reports", brokentoolreportsheets_path %> ]
    </div>
  </div>
</div>

<% end %>

app/views/brokentoolreportsheets/new.html.erb
<h1>Report new broken tool for collection</h1>
<!-- this is a HTML file with embedded Ruby code to create a form to capture user input
      I partitioned the form with 'divs'into three main parts to suit the UC1 SFR steps
      and offered to cancel the process at for SFR6 step 3a-->
<%= form_for @brokentoolreportsheet do |f| %>
         <div>
           <%= f.label :toolname %> 
           <%= f.text_field :toolname, placeholder: "Name of tool", autofocus: true %>
         </div>

        <div>
          <%= f.label :toolfault %>
        </div>
        <div>
          <%= f.text_area :toolfault, rows:10, placeholder: "Description of fault" %>
        </div>

        <div>
          <%= f.label :toollocation %>
          <%= f.text_field :toollocation, placeholder: "Factory name" %>
        </div>
          
        <div>
          <!-- Asking confirmation from user for SFR6 step 3a -->
          <%= f.submit :onclick =>"return confirm('Sure')", class: "btn btn-primary btn-lg" %>
        </div>
      
    <% end %>
    
        <%= link_to "return to all tool faulty tool reports", brokentoolreportsheets_path %> 
  

app/views/brokentoolreportsheets/show.html.erb
<h1>Single broken tool report</h1>
<p><%= @brokentoolreportsheet.toolname %></p>
<p><%= @brokentoolreportsheet.toolfault %></p>
<p><%= @brokentoolreportsheet.toollocation %></p>
<p><%= link_to "Record new broken tool for collection", new_brokentoolreportsheet_path %></p>
<p><%= link_to "Display list of recorded broken tools", brokentoolreportsheets_path %></p>

app/views/factories/index.html.erb
<h1>All factories</h1>
<% @factories.each do |f| %>
<h2>Factory Name: <%= link_to f.name, factory_path(f) %></h2>
<p>Factory ID: <%= f.id %></p>
<p><%= f.address %></p>
<% end %>

<p><%= link_to "Home", root_path %></p>

app/views/factories/new.html.erb
<h1>Add a new factory</h1>

<!-- this is a HTML file with embedded Ruby code to create a form to capture user input
      I partitioned the form with 'divs'into three main parts to suit the UC1 SFR steps
      and offered to cancel the process at for SFR6 step 3a-->
<%= form_for @factory do |f| %>
         <div>
           <%= f.label :name %> 
           <%= f.text_field :name, placeholder: "Name of factory", autofocus: true %>
         </div>

        <div>
          <%= f.label :address %>
        </div>
        <div>
          <%= f.text_field :address, rows:5, placeholder: "Address of factory" %>
        </div>
          
        <div>
          <!-- Asking confirmation from user for SFR -->
          <%= f.submit :onclick =>"return confirm('Sure')", class: "btn btn-primary btn-lg" %>
        </div>
      
    <% end %>
    
         
  

app/views/factories/show.html.erb
<div class="factory">
    <h1>Recorded Factory's Details</h1>
    <p>Factory name: <%= @factory.name %></p>
    <p>Factory ID: <%= @factory.id %></p>
    <p>Factory Address: <%= @factory.address%></p>
</div>
----------------------------------------------------

<% @factory.vendingmachines.each do |v| %>

<p>Machine ID: <%= v.id %></p>
<p>Machine Name: <%= v.title %></p>

<p><%= link_to "Record new stock check" , new_stockchecksheet_path(v) %></p>

<p><%= link_to "Record vending machine fault", new_faultsheet_path(v) %></p>




----------------------------------------------------


<% end %>

<p><%= link_to "Add new vending machine", new_vendingmachine_path %></p>
<p><%= link_to "Record new factory", new_factory_path %></p>

<p><%= link_to "Home Page", root_path %></p>

app/views/faultsheets/new.html.erb
<h1>Record new fault sheet</h1>

<%= form_for @faultsheet do |f| %>

<div>
  <%= f.label :Fault_noticed %>
</div>
<div>
  <%= f.text_area :fault , rows: 10, placeholder: "Enter vending machine fault", autofocus: true %>
</div>
<div>
  <%= f.label :Machine_ID %>
</div>
<div>
  <%= f.text_field :vendingmachine_id, placeholder: "enter machine ID", autofocus: true %>
</div>
<div>
  <!-- Asking confirmation from user for SFR6 step 3a -->
  <%= f.submit :onclick =>"return confirm('Sure')", class: "btn btn-primary btn-lg" %>
</div>
<% end %>

app/views/faultsheets/show.html.erb
<h1>Recorded fault</h1>

<p>Fault: <%= @faultsheet.fault %></p>
<p><%= link_to "Record new fault", new_faultsheet_path %></p>
<p><%= link_to "Home Page", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stockchecksheets/checkstock.html.erb
<p>stockcheck.html.erb </p>
<% @sheets.each do |s| %>
<p><%= s.item1 %></p>
<p><%= s.item2 %></p>
<p><%= s.item3 %></p>
<p><%= s.item4 %></p>
<p><%= s.item5 %></p>
<% end %>

app/views/stockchecksheets/index.html.erb
<h1>List of stock check sheet for machine</h1>
<% @sheet.each do |s| %>
<p><%= s.item1 %></p>
<p><%= s.item2 %></p>
<p><%= s.item3 %></p>
<p><%= s.item4 %></p>
<p><%= s.item5 %></p>
-------------------------------------------
<% end %>

app/views/stockchecksheets/new.html.erb
<h1>Record new stock check sheet</h1>

<!-- this is a HTML file with embedded Ruby code to create a form to capture user input -->
     
<%= form_for @sheet do |f| %>
        <div>
          <%= f.label :item_1 %> 
          <%= f.text_field :item1, placeholder: "enter item", autofocus: true %>
        </div>
        
        <div>
           <%= f.label :item_2 %> 
           <%= f.text_field :item2, placeholder: "enter item", autofocus: true %>
         </div>
         
         <div>
           <%= f.label :item_3 %> 
           <%= f.text_field :item3, placeholder: "enter item", autofocus: true %>
         </div>
         
         <div>
           <%= f.label :item_4 %> 
           <%= f.text_field :item4, placeholder: "enter item", autofocus: true %>
         </div>
         
         <div>
           <%= f.label :item_5 %> 
           <%= f.text_field :item5, placeholder: "enter item", autofocus: true %>
         </div>
         
          <div>
           <%= f.label :Machine_ID %> 
           <%= f.text_field :vendingmachine_id, placeholder: "enter machine ID", autofocus: true %>
         </div>
         
        <div>
          <!-- Asking confirmation from user for SFR -->
          <%= f.submit :onclick =>"return confirm('Sure')", class: "btn btn-primary btn-lg" %>
        </div>
        
      
    <% end %>

app/views/stockchecksheets/show.html.erb
<h1>Stock check sheet details</h1>

    <p>Vending Machine ID: <%= @sheet.vendingmachine_id %></p>
    
    <%= form_for @sheet do |f| %>
        <div>
          <p>Item 1 : <%= @sheet.item1 %></p>
          <%= f.label :On_screen %> 
          <%= f.text_field :item11, placeholder: "enter qty" %>
          <%= f.label :Physical %>
          <%= f.text_field :item12, placeholder: "enter qty" %>
        </div>
---------------------------------------------------------------------------------------        
        <div>
          <p>Item 2 : <%= @sheet.item2 %></p>
          <%= f.label :On_screen %> 
          <%= f.text_field :item21, placeholder: "enter qty" %>
          <%= f.label :Physical %>
          <%= f.text_field :item22, placeholder: "enter qty" %>
        </div>
---------------------------------------------------------------------------------------
        <div>
          <p>Item 3 : <%= @sheet.item3 %></p>
          <%= f.label :On_screen %> 
          <%= f.text_field :item31, placeholder: "enter qty" %>
          <%= f.label :Physical %>
          <%= f.text_field :item32, placeholder: "enter qty" %>
        </div>
---------------------------------------------------------------------------------------
        <div>
          <p>Item 4 : <%= @sheet.item4 %></p>
          <%= f.label :On_screen %> 
          <%= f.text_field :item41, placeholder: "enter qty" %>
          <%= f.label :Physical %>
          <%= f.text_field :item42, placeholder: "enter qty" %>
        </div>
---------------------------------------------------------------------------------------
        <div>
          <p>Item 5 : <%= @sheet.item5 %></p>
          <%= f.label :On_screen %> 
          <%= f.text_field :item51, placeholder: "enter qty" %>
          <%= f.label :Physical %>
          <%= f.text_field :item52, placeholder: "enter qty" %>
        </div>
---------------------------------------------------------------------------------------

        <div>
          <!-- Asking confirmation from user for SFR -->
          <%= f.submit :onclick =>"return confirm('Sure')", class: "btn btn-primary btn-lg" %>
        </div>
        
      
    <% end %>
<p><%= link_to "Do another stock check" , vendingmachines_path(@machines) %></p>    
<p><%= link_to "Home Page", root_path %></p>

app/views/vendingmachines/index.html.erb
<h1>All Vendingmachines</h1>
<% @vendingmachines.each do |f| %>
<h2>Vending machine name: <%=link_to f.title, vendingmachine_path(f) %></h2>
<p>Machine ID: <%= f.id %></p>
<p>Factory ID: <%= f.factory_id %></p>
<p>Vending macine configuration: <%= f.configuration %></p>
-----------------------------------------------------------------------------

<% end %>

app/views/vendingmachines/new.html.erb
<h1>Add a new vending machine</h1>

<!-- this is a HTML file with embedded Ruby code to create a form to capture user input
      I partitioned the form with 'divs'into three main parts to suit the UC1 SFR steps
      and offered to cancel the process at for SFR6 step 3a-->
<%= form_for @vendingmachine do |f| %>
         <div>
           <%= f.label :title %> 
           <%= f.text_field :title, placeholder: "vending machine's name", autofocus: true %>
         </div>

        <div>
          <%= f.label :configuration %>
          <%= f.text_field :configuration, rows:5, placeholder: "configuration of vending machine" %>
        </div>
        
        <div>
          <%= f.label :Factory_Identification_number %>
          <%= f.text_field :factory_id, placeholder: "enter factory ID" %>
        </div>
      
        <div>
          <!-- Asking confirmation from user for SFR -->
          <%= f.submit :onclick =>"return confirm('Sure')", class: "btn btn-primary btn-lg" %>
        </div>
        
      
    <% end %>

app/views/vendingmachines/show.html.erb
<h1>Vendingmachine</h1>
<p>Machine name: <%= @vendingmachine.title %></p>
<p>Configuration: <%= @vendingmachine.configuration %></p>
<p>Machine ID: <%= @vendingmachine.id %></p>

<p>Select stock check sheet from list: </p>
<% @stockchecksheets.each do |s| %>
<ul>
  <li><%= link_to s.id , stockchecksheet_path(s) %></li>
</ul>
<% end %>




<p><%= link_to "Home screen", root_path %></p>
<p><%= link_to "Add new vending machine", new_vendingmachine_path %> </p>
<p><%= link_to "Record items for stock check", new_stockchecksheet_path %></p>

app/views/welcome/index.html.erb
<h1>workmateApp Homepage</h1>

<div>
  <%= link_to "Record new broken tool for collection", new_brokentoolreportsheet_path %> | 
  <%= link_to "Display list of recorded broken tools", brokentoolreportsheets_path %>
</div> 

<div>
  <%= link_to "Add a new factory", new_factory_path %>
</div>

<div>
  <%= link_to "Record new vending machine", factories_path %>
</div>


<div>
  <%= link_to "Create new stock check list", factories_path %> |
  <%= link_to "View items for stock check for a vendingmachine", vendingmachines_path %>
</div>

<div>
  <%= link_to "Record vending machine fault", factories_path %>
</div>